accounts/urls.py
from django.contrib import admin
from django.urls import path
from accounts import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "accounts"

urlpatterns = [
    path('', views.hello, name='hello'),
    path('home', views.home, name="home"),
    path("login/", views.Login, name="login"),  # Ensure this matches "Login"
    path("register/", views.register, name="register"),
    path("logout/", views.Logout, name="logout"),  # Ensure this matches "Logout"
    # other paths...
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

feed/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name= "feed"

urlpatterns = [
    path('admin/', admin.site.urls),
    path("home/",views.home,name="home"),
    path("create-post/",views.create_post,name="create_post"),
    path("delete/<int:id>/",views.delete_post,name="delete_post"),
    path("update/<int:id>/",views.update_post,name="update_post"),
    path("like/<int:id>/",views.like_post,name="like_post"),
    path('post/<int:id>/comment/', views.comment_post, name='comment_post'),
    path("comments/",views.comment_list,name="all comments"),
    path('profile/<str:username>/', views.profile_view, name='profile'),
    path('profile/edit/<str:username>/', views.profile_edit, name='profile_edit'),
    path('search/', views.search_posts, name='search_posts'),
    # Profile edit page for the logged-in user
    
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts.urls import *
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import Login

urlpatterns = [

    path('admin/', admin.site.urls),
    path("",Login,name="Login"),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('feed/', include(('feed.urls', 'feed'), namespace='feed')),
    path('accounts/', include('allauth.urls')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Django project</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <style>
            nav{
                background: linear-gradient(90deg, rgba(200,199,216,1) 0%, rgba(99,95,95,1) 35%);
            }
            
        </style>
    </head>
    <body>
        {% block nav %}

        <nav class="navbar navbar-expand-lg">
            <div class="container-fluid"  id="nav">
              <a class="navbar-brand" href="#">Navbar</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  
                  
                  
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'feed:home' %}">Home</a>
                  </li>
                  {% if user.is_authenticated %}
                  <li class="nav-item">
                  {% if profile %}
                  
                 
                 
                    <a class="nav-link" href="{% url 'feed:profile' request.user.username %}">Profile</a>
                  </li>
                  {% else %}
                  <a class="nav-link" href="{% url 'feed:profile_edit' request.user.username %}">create Profile</a>

                   {% endif %}
                  {% endif%}
                  
                  
                </ul>
                <form method="GET" action="{% url 'feed:search_posts' %}">
                  <input type="text" name="q" placeholder="Search posts or users">
                  <button type="submit">Search</button>
              </form>
               
                 
            
                {% if user.is_authenticated %}
                <button class="btn btn-outline-danger" type="submit"><a href="{% url 'accounts:logout' %}">Logout</a></button>
                 {% else %} 
                 <button class="btn btn-primary" type="submit"><a href="{% url 'accounts:login'%}" style="color:antiquewhite">Login</a></button>
                 <button class="btn btn-primary" type="submit"><a href="{% url 'accounts:register'%}" style="color:orange">Signup</a></button>
                  {% endif %}
                </div>
              
            </div>
          </nav>
          {% endblock nav %}
        <script src="" async defer></script>
    </body>
</html>

templates/comment_list.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>ALl comment s</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        All comments 
        <ul>
            {% for  comment in comments %}
            <li>
                <strong>{{comment.user.username}}</strong>:{{comment.caption}}
            </li>
            {% endfor %}
        </ul>
        
        <script src="" async defer></script>
    </body>
</html>

templates/delete.html
<h1>delete Post here</h1>
<h1>Are You Sure You want to delete Your Post </h1>
<p>{{post.caption}}</p>

<form method= 'POST'>

    {% csrf_token %}
    
    <button type="submit"> delete </button>
    <a href="{% url "feed:home" %}">cancel</a>
</form>

templates/form.html
<!-- templates/simple_form.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Simple Form</title>
</head>
<body>
    <h1>Simple Form</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        
        <button type="submit">Submit</button>
    </form>
</body>
</html>

templates/home.html
{% include "base.html" %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        {%block content%}
        <button type="button" class="btn btn-primary"><a href="{% url "create_post" %}" style="color:white">create</a></button>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% for post in  posts %}
        <div>
    
       
        {% if post.image %}
            <br>
            <br>
            <img src="{{ post.image.url }}" width="200" alt="post image">
            <p>{{ post.caption }}</p>
            
            <button type="button" class="btn btn-danger"><a href="{% url "delete_post"  post.id %}" style="color:white">delete</a></button>
            <button type="button" class="btn btn-primary"><a href="{% url "update_post"  post.id %}" style="color:white">Edit</a></button>

            <br>
        {% else %}
        <p>No image available</p>

        {% endif %}
        </div>
        {% endfor %}
        {%endblock %}
        <script src="" async defer></script>
    </body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="/css/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <div class="row">
            <div class="col-md-4" id="sidebar">
                <img src="/media/hello.jpg" alt="" id="img">

                <h4 id="text">Shreyansh Singh Bhati</h4>

            </div>
            <div class="col-md-8" id="card">
                <div class="card"  >
                    <img src="https://mdbcdn.b-cdn.net/img/new/standard/nature/184.webp" class="card-img-top" alt="Fissure in Sandstone"/>
                    <div class="card-body">
                      <h5 class="card-title">Card title</h5>
                      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                      <a href="#!" class="btn btn-primary" data-mdb-ripple-init>Button</a>
                    </div>
                  </div>
            </div>


        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>

</html>

templates/signup_form.html
{%extends 'login.html'%}
{%block nav %}
<h1>hello world</h1>
{%endblock%}

templates/update.html
<h1>Update Page</h1>
<form method= 'POST' enctype="multipart/form-data">
    {% csrf_token %}  
    {{form.as_p}}
    <button type="submit"> update</button>
    
</form>

templates/user_profile.html
{% include "base.html" %}

 <!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
        <style>
        #sidebar{
    background: linear-gradient(to right , grey , white);
    height: 100vh;
    border: 2px solid black;
    border-top: none;
    border-left: none;
    border-bottom: none;
    
}

#img{
    border-radius: 50%;
    height: 100px;
    width: 100px;
    margin-top: 30px;
    margin-left: 30px;
}

#text{
    margin-top: 20px;
    margin-left: 60px;
}


#card{
    margin-top: 20px;
    box-shadow: 3px 4px 5px grey;
   
}

        </style>
</head>

<body>
<h1 style='color:red; text-align:center;'>posts</h1>
    <div class="container">
        <div class="row">
            <div class="col-md-4" id="sidebar">
            <h2>{{ user_profile.username }}'s Profile</h2>
    
    <!-- Profile Picture and Bio -->
    <div class="profile-info">

    {% if  profile.profile_picture %}
    
        <img src="{{ profile.profile_picture.url }}" alt="Profile Picture">
        <p><strong>Bio:</strong> {{ profile.bio }}</p>
         {% endif %}
    </div>
   
    {% if request.user.username == user_profile.username %}
    <a href="{% url 'feed:profile_edit' request.user.username %}">Edit Profile</a>
    {% endif %}
    </div>
            
            {% for post in posts  %}
            <div class="col-md-8" id="card">
                <div class="card"  >
                <div class="posts-section">
            <h3></h3>
                {% if post.image %}
                    <div class="photo">
                      <img src="{{post.image.url}}" alt="" >
                {% endif %}
                    </div>
     
                    
                    <div class="card-body">
                      <h5 class="card-title"></h5>
                      
                      <p class="card-text">{{post.caption}}</p>
                      
                      <a href="{% url "feed:update_post" post.id %}" class="btn btn-primary" data-mdb-ripple-init><i class="bi bi-pencil-square" style="color:green;"></i></a>
                      <a href="{% url "feed:delete_post" post.id %}" ><i class="bi bi-trash3-fill" style="color: red;"></i></a>
                    
                      <li><strong>Likes --></strong>{{ post.Like.count}}  </li>
                      
                     <div class="comments text-muted">
                     <ul>
                              {% for comment in post.comments.all %}
                              <li><strong>{{ comment.user.username }}</strong> -{{ comment.caption }}  </li>
                              {% endfor %}
                           
                              
                            </ul>
                          
                       
                    </div>
                    </div>
                  </div>
            </div>
            {% endfor%}


        </div>
    </div>
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>

</html>

templates/verify_otp.html
{% include "base.html" %}

{% block content %}
<h1>Authentication page</h1>
{%endblock%}


<form method= 'POST'>
    {% if messages %}
    <div class="alert alert-danger" role="alert">
        
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
        {% endif %}
      
    
    {% csrf_token %}
    <input type='text' name='user_otp' placeholder="Enter Your OTP" required>
    <button type="submit"> submit</button>
</form>